server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Fallback routing untuk React Router (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimalisasi caching untuk file statis (Vite men-generate hash di nama file)
    location ~* \.(?:css|js|jpg|svg|png|woff2?|eot|ttf|otf|ico)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
    }
}